#key(command~.do)=value(package...classsname)

#/list.do=action.ListAction
/index.do=action.IndexAction
#/main.do=action.MainAction
#/choice01.do=action.ChoiceAction

/admin/AdminMain.do=action.AdminMainAction
/admin/mbList.do=action.MemberListAction
/admin/Register.do=action.MbRegisterAction
/admin/PersonInsert.do=action.PersonInsertAction




# /member/list.do