CREATE TABLE IF NOT EXISTS USER(
	USERID CHAR(20),
	USERNAME CHAR(20),
	PASSWORD CHAR(20),
	POSTCODE CHAR(8),
	ADDRESS CHAR(50),
	EMAIL CHAR(50),
	JOB CHAR(30),
    BIRTHDAY DATE,
	PRIMARY KEY (USERID)
);
